# originally taken from https://github.com/python-poetry/poetry/blob/master/.pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=2000']
#        exclude: ^.*\.egg-info/
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements

  - repo: https://github.com/jlebar/pre-commit-hooks
    rev: 62ca83ba4958da48ea44d9f24cd0aa58633376c7 # pragma: allowlist secret
    hooks:
      - id: do-not-submit # Forbids the string "do not submit".upper()
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: "isort (python)"
        types: [python]
      - id: isort
        name: "isort (pyi)"
        types: [pyi]
        args: [--lines-after-imports, "-1"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ '-l', '120' ]