[tool.isort]
profile = "black"
line_length = 120
include_trailing_comma = "True"
lines_after_imports = 2
lines_between_types = 1
known_lessmore = "lessmore"
combine_as_imports = "True"
known_first_party = []
sections = "FUTURE,STDLIB,THIRDPARTY,LESSMORE,FIRSTPARTY,LOCALFOLDER"
