word_collection = {
    "basics1": [
        # Nouns
        "das Haus; der Garten",
        "der Baum; die Blume",
        "das Auto; das Fahrrad",
        "der Tisch; der Stuhl",
        "Book: das Buch; das Kapitel; die Seite; die Zeile; das Wort",
        "der Bleistift; der Kugelschreiber",
        "der Hund; die Katze",
        "der Freund; der Feind",
        "das Kind; der Erwachsene",
        "das Wasser; die Erde; das Feuer; die Luft",
        "das Brot; die Butter",
        "der Apfel; die Orange",
        "der Kindergarten; die Schule; die Universität",
        "die Stadt; das Dorf",
        "die Straße",
        "das Zimmer",
        "der Tag; die Nacht",
        "Time: das Jahr; der Monat; die Woche; der Tag; die Stunde; die Minute; die Sekunde",
        "der Vater; die Mutter",
        "der Bruder; die Schwester",
        "die Zeit; der Raum",
        # Verbs
        "sein; haben",
        "kommen; gehen",
        "sehen; hören; fühlen",
        "essen; trinken",
        "schlafen; aufwachen",
        "lesen; schreiben",
        "sprechen; schweigen",
        "lernen; lehren",
        "arbeiten; ausruhen",
        "die Arbeit; die Freizeit",
        "spielen",
        "laufen",
        "fahren",
        "kaufen; verkaufen",
        "geben; nehmen",
        "finden; verlieren",
        "fragen; antworten",
        "wohnen; sterben; das Leben; der Tod",
    ],
    "greetings": [
        "Hallo",
        "Morgen",
        "Abend",
        "Guten Morgen",
        "Guten Tag",
        "Guten Abend",
        "Gute Nacht",
        "Mahl",
        "Tschüss",
        "Auf Wiedersehen",
        "Wieder",
        "Servus",
        "Moin",
        "Grüß",
        "Gott",
        "dich",
        "Grüß Gott",
        "Grüß dich",
        "Mahlzeit",
        "Willkommen",
        "Hi",
        "Hey",
    ],
    "travel": [
        "gehen",
        "fahren",
        "laufen",
        "fliegen",
        "reisen",
        "wandern",
        "marschieren",
        "schwimmen",
        "reiten",
        "ziehen",
    ],
    "communication": [
        "fragen",
        "antworten",
        "sagen",
        "sprechen",
        "erzählen",
        "diskutieren",
        "erklären",
        "reden",
        "melden",
        "berichten",
    ],
}
