word_groups = {
    "basics1": [
        # Nouns
        "das Haus und der Garten",
        "der Baum und die Blume",
        "das Auto und das Fahrrad",
        "der Tisch und der Stuhl",
        "das Buch, das Kapitel, die Seite, die Zeile, das Wort",
        "der Bleistift und der Kugelschreiber",
        "der Hund und die Katze",
        "der Freund und der Feind",
        "das Kind und der Erwachsene",
        "das Feuer, das Wasser, die Luft, die Erde",
        "das Brot und die Butter",
        "der Apfel und die Orange",
        "der Kindergarten, die Schule, die Universität",
        "die Stadt und das Dorf",
        "die Straße",
        "das Zimmer",
        "der Tag und die Nacht",
        "die Minute, die Stunde, das Jahr, der Monat, die Woche, der Tag",
        "der Vater und die Mutter",
        "der Bruder und die Schwester",
        "die Zeit und der Raum",
        # Verbs
        "sein und haben",
        "kommen und gehen",
        "sehen, hören, fühlen",
        "essen und trinken",
        "schlafen und aufwachen",
        "lesen und schreiben",
        "sprechen und schweigen",
        "lernen und lehren",
        "arbeiten und ausruhen, die Arbeit und die Freizeit",
        "spielen",
        "laufen",
        "fahren",
        "kaufen und verkaufen",
        "geben und nehmen",
        "finden und verlieren",
        "fragen und antworten",
        "wohnen und sterben, das Leben und der Tod",
    ],
    "titles": [
        "Harry Potter und der Stein der Weisen",
        "Harry Potter und die Kammer des Schreckens",
        "Harry Potter und der Gefangene von Askaban",
        "Harry Potter und der Feuerkelch",
        "Harry Potter und der Orden des Phönix",
        "Harry Potter und der Halbblutprinz",
        "Harry Potter und die Heiligtümer des Todes",
        "Der Herr der Ringe: Die Gefährten",
        "Der Herr der Ringe: Die zwei Türme",
        "Der Herr der Ringe: Die Rückkehr des Königs",
    ],
    "travel": [
        "gehen",
        "fahren",
        "laufen",
        "fliegen",
        "reisen",
        "wandern",
        "marschieren",
        "schwimmen",
        "reiten",
        "ziehen",
    ],
    "communication": [
        "fragen",
        "antworten",
        "sagen",
        "sprechen",
        "erzählen",
        "diskutieren",
        "erklären",
        "reden",
        "melden",
        "berichten",
    ],
}
