word_groups = {
    "basics1": [
        # Nouns
        "Haus und Garten",
        "Baum und Blume",
        "Auto und Fahrrad",
        "Tisch und Stuhl",
        "Buch, Kapitel, Seite, Zeile, Wort",
        "Bleistift und Kugelschreiber",
        "Hund und Katze",
        "Freund und Feind",
        "Kind und Erwachsener",
        "Feuer, Wasser, Luft, Erde",
        "Brot und Butter",
        "Apfel und Orange",
        "Kindergarten, Schule, Universität",
        "Stadt und Dorf",
        "Straße",
        "Zimmer",
        "Tag und Nacht",
        "Minute, Stunde, Jahr, Monat, Woche, Tag",
        "Vater und Mutter",
        "Bruder und Schwester",
        "Zeit und Raum",
        # Verbs
        "sein und haben",
        "kommen und gehen",
        "sehen, hören, fühlen",
        "essen und trinken",
        "schlafen und aufwachen",
        "lesen und schreiben",
        "sprechen und schweigen",
        "lernen und lehren",
        "arbeiten und ausruhen, Arbeit und Freizeit",
        "spielen",
        "laufen",
        "fahren",
        "kaufen und verkaufen",
        "geben und nehmen",
        "finden und verlieren",
        "fragen und antworten",
        "wohnen und sterben, Leben und Tod",
    ],
    "ver-verbs": [
        "kaufen",
        "verkaufen",
        "mieten",
        "vermieten",
        "binden",
        "verbinden",
        "brennen",
        "verbrennen",
        "brauchen",
        "verbrauchen",
        "teilen",
        "verteilen",
        "geben",
        "vergeben",
        "suchen",
        "versuchen",
        "stehen",
        "verstehen",
        "ändern",
        "verändern",
        "meiden",
        "vermeiden",
        "schwinden",
        "verschwinden",
        "sammeln",
        "versammeln",
        "wenden",
        "verwenden",
        "langen",
        "verlangen",
        "folgen",
        "verfolgen",
        "bleiben",
        "verbleiben",
        "treiben",
        "vertreiben",
        "schaffen",
        "verschaffen",
        "leihen",
        "verleihen",
        "leiten",
        "verleiten",
        "stehen",
        "verstehen",
        "ziehen",
        "verziehen",
        "arbeiten",
        "verarbeiten",
        "führen",
        "verführen",
        "halten",
        "verhalten",
        "lernen",
        "verlernen",
        "passen",
        "verpassen",
        "schreiben",
        "verschreiben",
        "zeihen",
        "verzeihen",
    ],
    "titles": [
        "Harry Potter und der Stein der Weisen",
        "Harry Potter und die Kammer des Schreckens",
        "Harry Potter und der Gefangene von Askaban",
        "Harry Potter und der Feuerkelch",
        "Harry Potter und der Orden des Phönix",
        "Harry Potter und der Halbblutprinz",
        "Harry Potter und die Heiligtümer des Todes",
        "Der Herr der Ringe: Die Gefährten",
        "Der Herr der Ringe: Die zwei Türme",
        "Der Herr der Ringe: Die Rückkehr des Königs",
    ],
    "travel": [
        "gehen",
        "fahren",
        "laufen",
        "fliegen",
        "reisen",
        "wandern",
        "marschieren",
        "schwimmen",
        "reiten",
        "ziehen",
    ],
    "communication": [
        "fragen",
        "antworten",
        "sagen",
        "sprechen",
        "erzählen",
        "diskutieren",
        "erklären",
        "reden",
        "melden",
        "berichten",
    ],
    "english-like": [
        "finden",
        "Haus",
        "Mutter",
        "Vater",
        "Katze",
        "Hund",
        "Apfel",
        "Name",
        "Buch",
        "Brot",
        "Wasser",
        "Hand",
        "Finger",
        "Telefon",
        "Musik",
        "Lampe",
        "Auto",
        "Kind",
        "Maus",
        "Glas",
        "Garten",
        "Milch",
        "Zucker",
        "Tee",
        "Salz",
        "Fisch",
        "Bier",
        "Schule",
        "Stuhl",
        "Tür",
        "Sonne",
        "Mond",
        "Stern",
        "Wolke",
        "Regen",
        "Schnee",
        "Wind",
        "Kalt",
        "Heiß",
        "Blau",
        "Grün",
        "Rot",
        "Braun",
        "Gelb",
        "Orange",
        "Zimmer",
        "Küche",
        "Bett",
        "Tisch",
        "Stadt",
        "Bus",
        "Taxi",
        "Flugzeug",
        "Schiff",
        "Fahrrad",
        "Motorrad",
        "Straße",
        "Park",
        "Bank",
        "Hotel",
        "Restaurant",
        "Supermarkt",
        "Polizei",
        "Feuerwehr",
        "Krankenhaus",
        "Museum",
        "Theater",
        "Konzert",
        "Sport",
        "Tennis",
        "Fußball",
        "Basketball",
        "Golf",
        "Schwimmen",
        "Yoga",
        "Tanzen",
        "Film",
        "Literatur",
        "Computer",
        "Internet",
        "Telefon",
        "Fernsehen",
        "Radio",
        "Magazin",
        "trinken",
        "lernen",
        "sprechen",
        "schlafen",
    ],
    "russian-like": [
        "Kamera",
        "Radio",
        "Telefon",
        "Computer",
        "Museum",
        "Restaurant",
        "Universität",
        "Hotel",
        "Theater",
        "Büro",
        "Doktor",
        "Oper",
        "Bank",
        "Park",
        "Zirkus",
        "Schule",
        "Bibliothek",
        "Student",
        "Studentin",
        "Professor",
        "Konferenz",
        "Musik",
        "Instrument",
        "Programm",
        "Politik",
        "Katastrophe",
        "Journalist",
        "Reporter",
        "Spezialist",
        "Pianist",
        "Artist",
        "Tourist",
        "Chef",
        "Ingenieur",
        "Technik",
        "Maschine",
        "Motor",
        "Kompetenz",
        "Funktion",
        "Organisation",
        "Information",
        "Diskussion",
        "Projekt",
        "System",
        "Labor",
        "Analyse",
        "Methode",
        "Statistik",
        "Strategie",
        "Taktik",
        "Disziplin",
        "Konzept",
        "Objekt",
        "Subjekt",
        "Struktur",
        "Prozess",
        "Mechanismus",
        "Prinzip",
        "Philosophie",
        "Psychologie",
        "Sociologie",
        "Biologie",
        "Chemie",
        "Physik",
        "Geologie",
        "Mathematik",
        "Technologie",
        "Ökologie",
        "Medizin",
        "Anästhesie",
        "Chirurgie",
        "Diagnose",
        "Therapie",
        "Immunität",
        "Allergie",
        "Vitamin",
        "Mineral",
        "Protein",
        "Kohlenhydrat",
        "Kalorie",
        "Diät",
        "Fitness",
        "Sport",
        "Basketball",
        "Volleyball",
        "Tennis",
        "Boxen",
        "Schach",
        "Ballett",
        "Oper",
        "Drama",
        "Komödie",
        "Film",
        "Serie",
        "Episode",
        "Szene",
        "Rolle",
        "Regisseur",
        "Produzent",
    ],
}
