TOPICS = [
    "Art",
    "Birthdays",
    "Clothes",
    "Daily Routine",
    "Dictionaries",
    "Evenings",
    "Mornings",
    "Family & Friends",
    "Food",
    "Hobbies",
    "Internet",
    "Leisure Time",
    "Music",
    "Neighbours & Neighbourhood",
    "News",
    "Pets",
    "Animals",
    "Reading",
    "Shopping",
    "Sport",
    "TV",
    "Transport",
    "Weather",
    "Book",
    "Communication",
    "Daily Routine",
    "Exercise",
    "Family",
    "Gift",
    "Journey",
    "Kindness",
    "Language",
    "Young people",
    "Old people",
    "Photograph",
    "Respect",
    "Trip",
    "Water",
    "Shopping",
]
