[tool.poetry]
name = "python3.10"
version = "0.1.0"
description = ""
authors = ["marklidenberg <marklidenberg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
cachetools = ">=4.0.0"
loguru = "^0.6.0"
environs = "^9.5.0"
python-dateutil = "^2.8.2"
path = "^16.4.0"
tqdm = "^4.64.0"
pydantic = "^1.9.2"
pendulum = "^2.1.2"
sortedcontainers = "^2.4.0"
python-telegram-bot = {version = "20.0a4", allow-prereleases = true}
Telethon = "1.24.0"
fire = "^0.4.0"
anyconfig = "^0.13.0"
requests = "^2.28.1"
ujson = "^5.5.0"
retry = "^0.9.2"
pyperclip = "^1.8.2"
more-itertools = "^9.0.0"
black = "^23.1.0"
"discord.py" = "^2.3.1"
openai = "^0.27.8"
inline-snapshot = "^0.3.2"
pytest = "^7.4.0"
pyyaml = "^6.0.1"
pymaybe = "^0.1.6"
better-exceptions = "^0.3.3"
emoji = "^2.8.0"
python-box = "^7.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
