[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "release-lessmore-service-example"
version = "0.1.0"
description = ""
authors = [ "marklidenberg <marklidenberg@gmail.com>",]

[tool.poetry.dependencies]
python = "3.12.3"

"lessmore.utils" = {git = "https://github.com/engineering-friends/lessmore.git", rev = "a44708fd819097cf9c94f111a9662aa5edf444fd", subdirectory = "source/python/libs/lessmore.utils"}
