name: pre-commit

on:
#  push:
#    branches: master
#  pull_request:
#    branches: [master]
  workflow_dispatch:


jobs:
  pre-commit:
    runs-on:
      - ubuntu-latest
    steps:
      # - Checkout

      - name: Checkout
        uses: actions/checkout@v3

      # - Включаем поддержку lfs (выключена для экономии траффика, т.к. здесь не нужна)
      #      - run: git lfs pull

      # - Pre-commit test

      - uses: pre-commit/action@v3.0.0